### ISSUE TITLE
Auto Re-Render?

### ISSUE THREAD

**Issue by BrinePlayz** [ichiriac/ejs-next#1]
Does It Support Next.js Auto Re-Render?

**Comment by ichiriac** [comment]
Hi,

Sorry for the late reply. I've never integrated it with Next.js so I can't answer. The name of the library may induce some confusion, I've called it like that as the `next` generation/version of EJS (not related to Next.js)

The big difference between my library and original implementation of EJS is that I handle async at any level so it may be implemented (+ some missing features from my point of view)
